# config.py - Централизованная конфигурация игры

# === ПАРАМЕТРЫ ЭКРАНА ===
SCREEN_WIDTH = 1200
SCREEN_HEIGHT = 800
FPS = 60

# === ЦВЕТА ===
WATER_BLUE = (20, 105, 180)
ISLAND_GREEN = (34, 139, 34)
DARK_GREEN = (25, 100, 25)
BROWN = (139, 69, 19)
WHITE = (255, 255, 255)
BLACK = (0, 0, 0)
RED = (220, 20, 20)
GOLD = (255, 215, 0)
CYAN = (0, 255, 255)

# === ИГРОК ===
PLAYER_SIZE = 50
PLAYER_BASE_SPEED = 3
PLAYER_MAX_HEALTH = 100
PLAYER_MAX_ANGLE = 45
PLAYER_ROTATION_SPEED = 1
PLAYER_AUTO_RETURN_SPEED = 1.5
PLAYER_SIDE_SPEED_MULTIPLIER = 3.0
PLAYER_SHOOT_COOLDOWN = 30  # frames
PLAYER_SHOOT_ANGLE_OFFSET = 20  # градусы
PLAYER_MIN_ANGLE_FOR_SIDE_SHOT = 5  # градусы
PLAYER_COLLISION_DAMAGE = 2
PLAYER_COLLISION_PUSHBACK = 15
PLAYER_EDGE_MARGIN = 100

# === СНАРЯДЫ ===
PROJECTILE_SPEED = 4.0
PROJECTILE_LIFETIME = 270  # frames (4.5 секунды при 60 FPS)
PROJECTILE_RADIUS = 5
PROJECTILE_COLOR_PLAYER = (255, 255, 0)
PROJECTILE_COLOR_ENEMY = (255, 50, 50)
PROJECTILE_DAMAGE_TO_PLAYER = 20

# === ОСТРОВА ===
ISLAND_MIN_RADIUS = 50
ISLAND_MAX_RADIUS = 120
ISLAND_SHAPE_POINTS = 20
ISLAND_SHAPE_NOISE_MIN = 0.85
ISLAND_SHAPE_NOISE_MAX = 1.15
ISLAND_COLLISION_MULTIPLIER = 0.8
ISLAND_STRUCTURES_MIN = 0
ISLAND_STRUCTURES_MAX = 2
ISLAND_DECORATIONS_MIN = 3
ISLAND_DECORATIONS_MAX = 8

# === БЕРЕГА ===
SHORE_WIDTH = 150
SHORE_INDENT_MIN = 40
SHORE_INDENT_MAX = 100
SHORE_SEGMENT_HEIGHT_MIN = 80
SHORE_SEGMENT_HEIGHT_MAX = 150
SHORE_EDGE_MARGIN = 200

# === ВРАГИ - ПРОСТЫЕ ===
ENEMY_SIMPLE_SIZE = 40
ENEMY_SIMPLE_BASE_SPEED = 2.2
ENEMY_SIMPLE_HEALTH = 1
ENEMY_SIMPLE_SHOOT_DELAY = 150  # frames
ENEMY_SIMPLE_POINTS = 100
ENEMY_SIMPLE_DETECTION_RANGE = 250
ENEMY_SIMPLE_AVOIDANCE_FORCE = 0.15
ENEMY_SIMPLE_TURN_SMOOTHNESS = 0.05
ENEMY_SIMPLE_ATTACK_CHANCE = 0.8  # 80% агрессивных
ENEMY_SIMPLE_PROJECTILE_SPEED = 3.5
ENEMY_SIMPLE_TORPEDO_DAMAGE = 30
ENEMY_SIMPLE_SPAWN_CHANCE = 0.25
ENEMY_SIMPLE_CAN_SEE_RANGE_X = 400
ENEMY_SIMPLE_CAN_SEE_RANGE_Y = 300

# === ВРАГИ - СЛОЖНЫЕ ===
ENEMY_HARD_SIZE = 60
ENEMY_HARD_BASE_SPEED = 1.6
ENEMY_HARD_HEALTH = 3
ENEMY_HARD_SHOOT_DELAY = 240  # frames
ENEMY_HARD_POINTS = 300
ENEMY_HARD_DETECTION_RANGE = 300
ENEMY_HARD_AVOIDANCE_FORCE = 0.2
ENEMY_HARD_TURN_SMOOTHNESS = 0.03
ENEMY_HARD_AGGRESSIVE_CHANCE = 0.7  # 70% агрессивных
ENEMY_HARD_PURSUIT_TIMER = 120  # frames памяти о игроке
ENEMY_HARD_PROJECTILES_COUNT = 3
ENEMY_HARD_PROJECTILE_SPEED = 2.8
ENEMY_HARD_PROJECTILE_SPREAD = 0.15  # радианы
ENEMY_HARD_TORPEDO_DAMAGE = 1000
ENEMY_HARD_SPAWN_CHANCE = 0.10
ENEMY_HARD_CAN_SEE_RANGE_X = 500
ENEMY_HARD_CAN_SEE_RANGE_Y = 400
ENEMY_HARD_ARMOR_FLASH_DURATION = 20  # frames
ENEMY_HARD_MIN_PATROL_DISTANCE = 300
ENEMY_HARD_PATROL_POINTS_MIN = 2
ENEMY_HARD_PATROL_POINTS_MAX = 2

# === ВОДОВОРОТЫ ===
WHIRLPOOL_RADIUS = 45
WHIRLPOOL_ROTATION_SPEED = 8
WHIRLPOOL_ANIMATION_SPEED = 0.1
WHIRLPOOL_PULSE_AMOUNT = 5
WHIRLPOOL_COOLDOWN = 180  # frames (3 секунды)
WHIRLPOOL_MIN_DISTANCE = 300
WHIRLPOOL_TELEPORT_DISTANCE = 1200
WHIRLPOOL_SPAWN_CHANCE = 0.1
WHIRLPOOL_MAX_COUNT = 6
WHIRLPOOL_PLACEMENT_ATTEMPTS = 20
WHIRLPOOL_PLAYER_OFFSET = -150  # offset от целевого водоворота
WHIRLPOOL_EDGE_MARGIN = 300
WHIRLPOOL_ISLAND_SAFE_DISTANCE = 50

# === ГЕНЕРАЦИЯ МИРА ===
WORLD_SEGMENT_HEIGHT = 2000
WORLD_GENERATION_AHEAD = 1500  # когда генерировать новый сегмент
WORLD_ISLAND_SPAWN_CHANCE = 0.85
WORLD_ISLAND_MIN_SPACING = 120
WORLD_ISLAND_RECENT_CHECK = 30  # сколько последних островов проверять
WORLD_ISLAND_STEP_MIN = 60
WORLD_ISLAND_STEP_MAX = 120
WORLD_ENEMY_SPAWN_DISTANCE = -1500  # враги только впереди игрока
WORLD_ENEMY_STEP_MIN = 100
WORLD_ENEMY_STEP_MAX = 200
WORLD_CLEANUP_DISTANCE = 2000  # удаление объектов позади игрока
WORLD_INITIAL_SEGMENTS = 3

# === КАМЕРА ===
CAMERA_OFFSET = 200

# === UI ===
UI_HEALTH_BAR_WIDTH = 250
UI_HEALTH_BAR_HEIGHT = 30
UI_PADDING = 20
UI_FONT_SIZE = 36
UI_SMALL_FONT_SIZE = 24
UI_BIG_FONT_SIZE = 48
UI_CONTROLS_WIDTH = 440
UI_CONTROLS_HEIGHT = 150
UI_GAME_OVER_WAIT = 4000  # milliseconds

# === АНИМАЦИЯ ===
WAVE_SPEED = 2
WAVE_HEIGHT = 40
TELEPORT_EFFECT_DURATION = 30  # frames

# === АКТИВАЦИЯ И ОЧИСТКА ===
ENEMY_ACTIVATION_DISTANCE = -2  # экранов от игрока
ENEMY_DELETE_DISTANCE = 3000  # пикселей позади игрока
WHIRLPOOL_DELETE_DISTANCE = 2000  # пикселей позади игрока

# === ФИЗИКА ===
COLLISION_RADIUS_PLAYER = PLAYER_SIZE // 2
COLLISION_RADIUS_ENEMY_SIMPLE = ENEMY_SIMPLE_SIZE // 2
COLLISION_RADIUS_ENEMY_HARD = ENEMY_HARD_SIZE // 2
SPAWN_CLEARANCE_RADIUS = 50
ENEMY_CLEARANCE_EXTRA = 50

# === КОНВЕРСИЯ ===
PIXELS_PER_MILE = 10  # для отображения расстояния