# file: postgresql/tasks/extensions/tds_fdw.yml

- name: PostgreSQL | Extensions | Make sure the postgres pg_cron extensions are installed | Debian
  apt:
    name: 
    - "freetds"
    - "freetds-devel"
    - "tds_fdw_{{ postgresql_version }}-llvmjit.x86_64"
    state: present
    update_cache: yes
    cache_valid_time: "{{ apt_cache_valid_time | default (3600) }}"
  when: ansible_os_family == "Debian"
  notify:
    - restart postgresql

- name: PostgreSQL | Extensions | Make sure the postgres pg_cron extensions are installed | RedHat
  yum:
    name: 
    - "freetds"
    - "freetds-devel"
    - "tds_fdw_{{ postgresql_version }}-llvmjit.x86_64"
    state: present
  when: ansible_pkg_mgr == "yum" and ansible_distribution == "RedHat"
  notify:
    - restart postgresql

- name: PostgreSQL | Extensions | Make sure the postgres pg_cron extensions are installed | Fedora
  dnf:
    name: 
    - "freetds"
    - "freetds-devel"
    - "tds_fdw_{{ postgresql_version }}-llvmjit.x86_64"
    state: present
  when: ansible_pkg_mgr == "dnf" and ansible_distribution == "Fedora"
  notify:
    - restart postgresql

- name: PostgreSQL | Extensions | Make sure the postgres pg_cron extensions are installed | Rocky
  dnf:
    name: 
    - "freetds"
    - "freetds-devel"
    - "tds_fdw_{{ postgresql_version }}-llvmjit.x86_64"
    state: present
  when: ansible_pkg_mgr == "dnf" and ansible_distribution == "Rocky"
  notify:
    - restart postgresql
